{
    "platform_info": {
        "error": "RequestException",
        "details": "HTTPSConnectionPool(host='10.10.7.1', port=12443): Max retries exceeded with url: /api/v1/platform (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))"
    },
    "allocators": {
        "error": "RequestException",
        "details": "HTTPSConnectionPool(host='10.10.7.1', port=12443): Max retries exceeded with url: /api/v1/platform/infrastructure/allocators (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))"
    },
    "deployments_details": []
}